function a = gmmLINactiv(mix, x,W)
%GMMACTIV Computes the activations of a Gaussian mixture model.
%
%	Description
%	This function computes the activations A (i.e. the  probability
%	P(X|J) of the data conditioned on each component density)  for a
%	Gaussian mixture model.  For the PPCA model, each activation is the
%	conditional probability of X given that it is generated by the
%	component subspace. The data structure MIX defines the mixture model,
%	while the matrix X contains the data vectors.  Each row of X
%	represents a single vector.
%
%	See also
%	GMM, GMMPOST, GMMPROB
%

%	Copyright (c) Ian T Nabney (1996-2001)

% Check that inputs are consistent
errstring = consist(mix, 'gmm', x);
if ~isempty(errstring)
  error(errstring);
end

switch mix.covar_type 
 case 'spherical'
  ndata = size(x, 1);
  a     = zeros(ndata, mix.ncentres); 
  normal = (2*pi)^(mix.nin/2);
  for j = 1:mix.ncentres
    diffs = x - (mix.centres(j, :) * W(j).w')';
    a(:, j) = exp(-0.5*sum(diffs.*diffs,2) / mix.covars(j)) ./ (normal*sqrt(mix.covars(j)));%% modif 27/11/09
    C     = inv(diag( mix.covars(j,:)));%% modif 27/11/09
    a(:, j) = exp(-0.5*(diffs' * C *diffs))./(normal*sqrt(det(C))); %% modif 27/11/09
  end
 otherwise
  error(['Unknown covariance type ', mix.covar_type,'for lin gmm']);
end
 
